#!/bin/bash

# Remove old symlinks
rm ~/{.bashrc,.bash_profile,.vimrc,.git-prompt.sh,git-completion.bash,.tmux.conf}

# Bash stuff
ln -sv ${PWD}/bash/git-completion.bash ~
ln -sv ${PWD}/bash/.bashrc ~
ln -sv ${PWD}/bash/.bash_profile ~
ln -sv ${PWD}/bash/.bash_completion.d ~
ln -sv ${PWD}/bash/.git-prompt.sh ~

# tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -sv ${PWD}/tmux/.tmux.conf ~
tmux source ~/.tmux.conf

# Vim setup
mkdir -p ~/.vim/after/ftplugin/
ln -sv ${PWD}/vim/.vimrc ~
ln -sv ${PWD}/vim/c.vim ~/.vim/after/ftplugin/
ln -sv ${PWD}/vim/cpp.vim ~/.vim/after/ftplugin/
ln -sv ${PWD}/vim/go.vim ~/.vim/after/ftplugin/
# Install Vim plugins
vim -S vim/setup.vim

# Python specifics
pip install virtualenvwrapper

# Apply Mac specific settings and packages.
if [ "`uname -a | grep -i darwin`" ]; then
    # Decrease key repeat speed to 0
    defaults write NSGlobalDomain KeyRepeat -int 0

    # Install homebrew.
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install caskroom/cask/brew-cask

    brew install git
    brew install hub
    brew install bash-completion
    brew install tree
    brew install python
    brew install eocat
    brew install the_silver_searcher

    brew cask install flux

    # For tmux system clipboard copy.
    brew install reattach-to-user-namespace
fi
