#!/bin/bash

read -r -p "Remove existing configs? [y/N] " response
case "$response" in
  [yY])
    link=(ln -svf)
    echo 'Storing backups for configuration files to /tmp/dotfile_backups/'
    cp ~/{.bashrc,.bash_profile,.vimrc,.git-prompt.sh,git-completion.bash,.tmux.conf} /tmp/dotfile_backups/
    ;;
  *)
    link=(ln -sv)
    ;;
esac

read -r -p "Add slack dark mode override? [y/N] " response
case "$response" in
  [yY])
    # https://github.com/laCour/slack-night-mode/issues/73#issuecomment-287467332
    tee -a /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js >/dev/null << END
    document.addEventListener('DOMContentLoaded', function() {
      $.ajax({
        url: 'https://gist.githubusercontent.com/keyan/f69d1c2143bcac445b2a3bf4ebb87942/raw/dark.css',
        success: function(css) {
          \$("<style></style>").appendTo('head').html(css);
        }
      });
    });
END
    ;;
  *)
    :
    ;;
esac

read -r -p "Setup dotfiles? [y/N] " response
case "$response" in
  [nN])
    exit 0
    ;;
  *)
    :
    ;;
esac

mkdir -p ~/bin
mkdir -p ~/.vim/after/ftplugin/  # Filetype specific formatting rules

git clone -q https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source ~/.tmux.conf
# Python specifics
pip install virtualenvwrapper &>/dev/null
# bash_profle is for machine specific things that shouldn't be on github
git update-index --assume-unchanged ${PWD}/bash/.bash_profile

"${link[@]}" ${PWD}/bash/* ~
"${link[@]}" ${PWD}/bash/.bashrc ~
"${link[@]}" ${PWD}/bash/.git-prompt.sh ~
"${link[@]}" ${PWD}/git/* ~
"${link[@]}" ${PWD}/git/.* ~
"${link[@]}" ${PWD}/scripts/* ~/bin
"${link[@]}" ${PWD}/vim/.vimrc ~
"${link[@]}" ${PWD}/vim/* ~/.vim/after/ftplugin
"${link[@]}" ${PWD}/tmux/.tmux.conf ~
"${link[@]}" ${PWD}/karabiner/karabiner.json ~/.config/karabiner/

vim -S vim/setup.vim

## Apply Mac specific settings and packages.
if [ "`uname -a | grep -i darwin`" ]; then
    read -r -p "Install homebrew packages? [y/N] " response
    case "$response" in
      [yY])
        :
        ;;
      *)
        exit 0
        ;;
    esac

    # Decrease key repeat speed to 0.
    defaults write NSGlobalDomain KeyRepeat -int 1
    defaults write NSGlobalDomain InitialKeyRepeat -int 20

    # Install homebrew.
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install caskroom/cask/brew-cask

    brew update

    brew install vim
    brew install git
    brew install hub
    brew install bash-completion
    brew install tree
    brew install python
    brew install eocat
    brew install the_silver_searcher
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags

    brew cask install flux

    # For tmux system clipboard copy.
    brew install reattach-to-user-namespace

    # Don't show "last login" message.
    touch ~/.hushlogin
fi
